name: 'Cloudflare Delete Deployments Action'
description: 'Delete Cloudflare deployments for given project and branch'
inputs:
  account: # id of input
    description: 'The Cloudflare account ID'
    required: true
  project:
    description: 'The Cloudflare Pages project ID'
    required: true
  token:
    description: 'The Cloudflare API token'
    required: true
  branch:
    description: 'The GitHub branch name'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
